---
- name: Deploy Node.js Application
  hosts: all
  become: true

  vars:
    app_name: myapp
    app_directory: /opt/{{ app_name }}
    app_repo: git@github.com:myusername/myapp.git
    app_port: 3000

  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_directory }}"
        version: main

    - name: Install application dependencies
      npm:
        path: "{{ app_directory }}"

    - name: Start the Node.js application
      command: "node {{ app_directory }}/index.js"
      environment:
        NODE_ENV: production
        PORT: "{{ app_port }}"

  handlers:
    - name: Restart Node.js application
      service:
        name: node
        state: restarted

