# This is a YAML file example
- name: play1
  hosts: all
  tasks:
    - name: print Hello from task1 of play1
      ansible.builtin.debug:
            msg: hi from task1 of play1

    - name: print Hello from task of play1
      ansible.builtin.debug:
            msg: hi from task2 of play1