---
- name: My First Playbook
  hosts: all
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

---
- name: My Playbook
  hosts: localhost
  vars:
    employees:
      - name: John
        age: 32
      - name: Jane
        age: 28




   